function show_instructions(~, ~)

    % The dialog
    dialog_pos_x=500;
    dialog_pos_y=200;
    dialog_width=500;
    dialog_height=450; 
    
    dialog_handle = dialog('Position',[dialog_pos_x dialog_pos_y dialog_width dialog_height],'Name','Instructions');
       
    % Title
    uicontrol('Parent',dialog_handle,...
           'Style','text',...
           'Position',[dialog_width/2-150 dialog_height-90 300 40],...
           'String','How to move in the image' ,...
            'FontName', 'arial',...
            'FontWeight', 'bold',...
            'FontSize', 10);
       
    % axes that span the whole dialog
    hImageAxes = axes('Parent', dialog_handle, 'Units', 'pixels', 'Position', [0 0 dialog_width dialog_height]);
    
    % The buttons
    [w,alpha_w] = get_key_image('w');
    [a,alpha_a] = get_key_image('a');
    [s,alpha_s] = get_key_image('s');
    [d,alpha_d] = get_key_image('d');
    [q,alpha_q] = get_key_image('q');
    [e,alpha_e] = get_key_image('e');

   
    instruction_wasd="Use W and S to rotate vertically, A and D to rotate horizontally";

    image(w,'AlphaData',alpha_w,'Parent',hImageAxes);
    uicontrol('Parent',dialog_handle,'Style','text',...
           'Position',[190 200 200 40],...
           'String',instruction_wasd,...
            'FontName', 'arial',...
            'FontSize', 8);
        
    [x,~] = imread('instruction_images/q.png'); 
    I2=imresize(x, [42 113]);
    uicontrol('units','pixels','position',[40 300 113 42],'cdata',I2,'Parent',dialog_handle);
    uicontrol('Parent',dialog_handle,'Style','text',...
           'Position',[190 300 200 40],...
           'String','Use Q and E to zoom in and out',...
            'FontName', 'arial',...
            'FontSize', 8);
        
    [x,~] = imread('instruction_images/e.png'); 
    I2=imresize(x, [42 113]);
    uicontrol('units','pixels','position',[40 100 113 42],'cdata',I2,'Parent',dialog_handle);
    uicontrol('Parent',dialog_handle,'Style','text',...
           'Position',[190 100 200 40],...
           'String','Use the arrows to pan in the image',...
            'FontName', 'arial',...
            'FontSize', 8);
          
    btn = uicontrol('Parent',dialog_handle,...
           'Position',[dialog_width/2-35 20 70 35],...
           'String','Close',...
           'Callback','delete(gcf)',...
           'Style', 'pushbutton',...
            'HorizontalAlignment', 'center',...
            'FontName', 'arial',...
            'FontWeight', 'bold',...
            'FontSize', 9);
       
    hImageAxes.Visible='off';
    
% Wait for d to close before running to completion
    uiwait(dialog_handle);
   
end

function [image, alpha]=get_key_image(button)
    [image,~,alpha] = imread(strcat('instruction_images/',button,'.png')); 
end