function tab1
    TabHandles = guidata(gcf);
    ButtonHeight = 40;
    NumberOfTabs = size(TabHandles, 1) - 2;
    PanelWidth = TabHandles{NumberOfTabs + 1, 2};
    PanelHeight = TabHandles{NumberOfTabs + 1, 3};
    White = [1 1 1];

    % Select Image Pushbutton
    uicontrol('Parent', TabHandles{1, 1}, ...
    'Units', 'pixels', ...
        'Position', [round(PanelWidth / 2) - 300 3 * ButtonHeight 200 ButtonHeight], ...
        'String', 'Select image', 'Callback', @SelectImageCallback, ...
        'Style', 'pushbutton', 'HorizontalAlignment', 'center', ...
        'FontName', 'arial', 'FontWeight', 'bold', 'FontSize', 12);

    % Open Image Pushbutton
    uicontrol('Parent', TabHandles{1, 1}, 'Units', 'pixels', ...
    'Position', [round(PanelWidth / 2) + 100 3 * ButtonHeight 200 ButtonHeight], ...
        'String', 'Upload image', 'Callback', @OpenImageCallback, ...
        'Style', 'pushbutton', 'HorizontalAlignment', 'center', ...
        'FontName', 'arial', 'FontWeight', 'bold', 'FontSize', 12);

    % Title
    uicontrol('Style', 'text', ...
    'Position', [round(PanelWidth / 4) 5 * ButtonHeight ...
            round(PanelWidth / 2) round(PanelHeight / 2)], ...
        'Parent', TabHandles{1, 1}, ...
        'string', "A tour into the picture", 'BackgroundColor', White, ...
        'HorizontalAlignment', 'center', 'FontName', 'arial', ...
        'FontWeight', 'bold', 'FontSize', 14);

    % Make tab 1 active
    tab_selected(0, 0, 1);
end
